debug: false
server:
  port: 8001
  error:
    include-stacktrace: never
spring:
  jackson:
    serialization:
      indent_output: true
  # jpa:  
    # hibernate:  
    #   ddl-auto: create  
    # database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://glintcore.net:5432/folio_release"  
    username: ldp  
    password: <>
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      # connectionTimeout: 20000
      maximumPoolSize: 5
