debug: false
server:
  port: 8001
  error:
    include-stacktrace: never
spring:
  jackson:
    serialization:
      indent_output: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USER}
    password: ${DB_PASS}
    continue-on-error: true
    # Keep the connection alive if idle for a long time (needed in production)
    testOnBorrow: true
    validationQuery: SELECT 1
    validationInterval: 30000
    hikari:
      connectionTimeout: 20000
      initialization-fail-timeout: -1
      maximumPoolSize: 5
